"""
Training data builder.

Assembles labeled training datasets from three sources, ordered by
label quality:

  1. Human-confirmed labels  (from FeedbackStore)         ← highest quality
  2. Synthetic demo data     (ground-truth labels known)
  3. Heuristic pseudo-labels (high-confidence heuristic
     predictions used as weak supervision)                ← lowest quality

The resulting DataFrame has:
  - One row per account
  - 39 feature columns (FEATURE_NAMES from feature_extractor.py)
  - A "label" column  (1 = bot, 0 = not bot)
  - A "label_source" column  ('human', 'synthetic', 'heuristic')
  - A "label_confidence" column  (0.0 – 1.0)

Public datasets
---------------
Twitter released several IRA (Internet Research Agency) datasets at:
  https://transparency.twitter.com/en/reports/information-operations.html

To load them, export your TSV as data/ira_users.tsv (user data) and
data/ira_tweets.tsv (tweet data), then call TrainingDataBuilder.load_ira_dataset().
The builder will merge them and assign label=1 with label_source='ira_official'.
"""

import json
import logging
from pathlib import Path
from collections import defaultdict

import numpy as np
import pandas as pd

from src.ml.feature_extractor import FeatureExtractor, FEATURE_NAMES

logger = logging.getLogger(__name__)

# Heuristic confidence thresholds for pseudo-labelling
PSEUDO_BOT_THRESHOLD = 0.70        # score >= this → pseudo-label as bot
PSEUDO_HUMAN_THRESHOLD = 0.25      # score <= this → pseudo-label as human
# Scores between the thresholds are discarded (too uncertain for pseudo-labels)


class TrainingDataBuilder:
    """Build a labeled training DataFrame from multiple data sources."""

    def __init__(self, config: dict | None = None):
        cfg = config or {}
        dis_cfg = cfg.get("disinformation", {})
        keywords = dis_cfg.get("keywords", {})
        state_media = set(dis_cfg.get("state_media_domains", []))
        self.extractor = FeatureExtractor(keywords=keywords, state_media=state_media)

    # ------------------------------------------------------------------
    # Source 1: Human-confirmed labels
    # ------------------------------------------------------------------

    def from_feedback(self, feedback_path: str) -> pd.DataFrame:
        """
        Load human-confirmed labels from a FeedbackStore JSON file.
        Returns an empty DataFrame if the file does not exist.
        """
        p = Path(feedback_path)
        if not p.exists():
            logger.info("No feedback file at %s – skipping", feedback_path)
            return pd.DataFrame()

        with open(p, "r") as f:
            data = json.load(f)

        entries = data.get("labels", [])
        if not entries:
            return pd.DataFrame()

        rows, labels, confidences, sources = [], [], [], []
        for entry in entries:
            feat = entry.get("features")
            label = entry.get("label")
            if feat is None or label is None:
                continue
            rows.append([feat.get(k, 0.0) for k in FEATURE_NAMES])
            labels.append(int(label))
            confidences.append(1.0)
            sources.append("human")

        df = pd.DataFrame(rows, columns=FEATURE_NAMES)
        df["label"] = labels
        df["label_confidence"] = confidences
        df["label_source"] = sources
        logger.info("Loaded %d human-confirmed labels", len(df))
        return df

    # ------------------------------------------------------------------
    # Source 2: Synthetic demo data (ground truth known)
    # ------------------------------------------------------------------

    def from_synthetic(self, n_accounts: int = 200) -> pd.DataFrame:
        """
        Generate synthetic accounts with known labels and extract features.
        Bot accounts: generated by demo.py with prefix bot_ or suspected_
        Human accounts: prefix human_
        """
        from src.demo import generate_demo_data

        logger.info("Generating %d synthetic accounts for training...", n_accounts)
        records = generate_demo_data(n_accounts=n_accounts)

        # Extract features
        from src.detectors.bot_detector import BotDetector
        detector = BotDetector()
        heuristic_scores = detector.score_all(records)

        features_df = self.extractor.extract_batch(records, heuristic_scores=heuristic_scores)

        # Determine true labels from account ID prefix
        labels, confidences, sources = [], [], []
        for uid in features_df.index:
            if uid.startswith("bot_"):
                labels.append(1)
                confidences.append(0.95)
            elif uid.startswith("suspected_"):
                labels.append(1)
                confidences.append(0.70)  # Lower confidence for suspected
            else:
                labels.append(0)
                confidences.append(0.95)
            sources.append("synthetic")

        features_df["label"] = labels
        features_df["label_confidence"] = confidences
        features_df["label_source"] = sources
        logger.info("Generated %d synthetic labeled samples", len(features_df))
        return features_df

    # ------------------------------------------------------------------
    # Source 3: Heuristic pseudo-labels
    # ------------------------------------------------------------------

    def from_heuristic_pseudolabels(
        self,
        records: list[dict],
        heuristic_scores: list[dict],
    ) -> pd.DataFrame:
        """
        Use high-confidence heuristic predictions as weak supervision.
        Only accounts with score >= PSEUDO_BOT_THRESHOLD or
        <= PSEUDO_HUMAN_THRESHOLD are included.
        """
        features_df = self.extractor.extract_batch(records, heuristic_scores=heuristic_scores)
        score_map = {
            (s.get("user_id") or (s.get("author") or {}).get("id")): s.get("bot_score", 0.5)
            for s in heuristic_scores
        }

        labels, confidences, sources, keep = [], [], [], []
        for uid in features_df.index:
            score = score_map.get(uid, 0.5)
            if score >= PSEUDO_BOT_THRESHOLD:
                labels.append(1)
                confidences.append(score)
                sources.append("heuristic")
                keep.append(True)
            elif score <= PSEUDO_HUMAN_THRESHOLD:
                labels.append(0)
                confidences.append(1.0 - score)
                sources.append("heuristic")
                keep.append(True)
            else:
                labels.append(-1)
                confidences.append(0.0)
                sources.append("uncertain")
                keep.append(False)

        features_df["label"] = labels
        features_df["label_confidence"] = confidences
        features_df["label_source"] = sources

        filtered = features_df[keep]
        logger.info(
            "Pseudo-labelled %d/%d accounts from heuristic (discarded %d uncertain)",
            len(filtered), len(features_df), len(features_df) - len(filtered),
        )
        return filtered

    # ------------------------------------------------------------------
    # Source 4: IRA official dataset (Twitter transparency data)
    # ------------------------------------------------------------------

    def load_ira_dataset(
        self,
        users_tsv: str = "data/ira_users.tsv",
        tweets_tsv: str = "data/ira_tweets.tsv",
    ) -> pd.DataFrame:
        """
        Load the official Twitter IRA dataset (TSV files downloaded from
        https://transparency.twitter.com).

        Expected columns in users_tsv:
            userid, user_display_name, user_screen_name, user_reported_location,
            user_profile_description, follower_count, following_count,
            account_creation_date, tweet_count, account_language

        Expected columns in tweets_tsv:
            userid, tweet_text, tweet_time, retweet_count, ...
        """
        from datetime import timezone

        up = Path(users_tsv)
        tp = Path(tweets_tsv)

        if not up.exists():
            logger.warning(
                "IRA users file not found: %s\n"
                "Download from https://transparency.twitter.com/en/reports/information-operations.html",
                users_tsv,
            )
            return pd.DataFrame()

        users_raw = pd.read_csv(up, sep="\t", dtype=str, low_memory=False)
        tweets_raw = pd.read_csv(tp, sep="\t", dtype=str, low_memory=False) if tp.exists() else None

        records = []
        tweets_by_user: dict[str, list[dict]] = defaultdict(list)

        if tweets_raw is not None:
            for _, row in tweets_raw.iterrows():
                uid = str(row.get("userid", ""))
                tweets_by_user[uid].append({
                    "text": str(row.get("tweet_text", "")),
                    "created_at": str(row.get("tweet_time", "")),
                    "referenced_tweets": (
                        [{"type": "retweeted", "id": "0"}]
                        if str(row.get("tweet_text", "")).startswith("RT ")
                        else []
                    ),
                    "entities": {},
                })

        now = pd.Timestamp.now(tz="UTC")
        for _, row in users_raw.iterrows():
            uid = str(row.get("userid", ""))
            created_str = str(row.get("account_creation_date", ""))
            try:
                created_dt = pd.to_datetime(created_str, utc=True)
                age_days = (now - created_dt).days
            except Exception:
                age_days = None

            user = {
                "id": uid,
                "username": str(row.get("user_screen_name", "")),
                "name": str(row.get("user_display_name", "")),
                "description": str(row.get("user_profile_description", "")),
                "location": str(row.get("user_reported_location", "")),
                "account_age_days": age_days,
                "followers_count": int(float(row.get("follower_count", 0) or 0)),
                "following_count": int(float(row.get("following_count", 0) or 0)),
                "tweet_count": int(float(row.get("tweet_count", 0) or 0)),
                "verified": False,
                "protected": False,
                "listed_count": 0,
                "profile_image_url": None,
            }
            tweet_record = {
                "id": f"ira_{uid}",
                "text": "",
                "author_id": uid,
                "created_at": None,
                "referenced_tweets": [],
                "entities": {},
                "author": user,
            }
            for t in tweets_by_user.get(uid, []):
                t["author_id"] = uid
                t["author"] = user
                records.append({**tweet_record, **t})

            if not tweets_by_user.get(uid):
                records.append(tweet_record)

        features_df = self.extractor.extract_batch(records)
        features_df["label"] = 1
        features_df["label_confidence"] = 1.0
        features_df["label_source"] = "ira_official"
        logger.info("Loaded %d IRA-labelled accounts", len(features_df))
        return features_df

    # ------------------------------------------------------------------
    # Merge and deduplicate
    # ------------------------------------------------------------------

    @staticmethod
    def merge(
        *dataframes: pd.DataFrame,
        priority: list[str] | None = None,
    ) -> pd.DataFrame:
        """
        Merge multiple labeled DataFrames, deduplicating by index.

        When an account appears in multiple sources, the highest-priority
        source wins. Default priority: human > ira_official > synthetic > heuristic.
        """
        priority = priority or ["human", "ira_official", "synthetic", "heuristic"]
        combined = pd.concat([df for df in dataframes if not df.empty], axis=0)

        if combined.empty:
            return combined

        # Sort by priority so the first occurrence of each uid wins
        source_rank = {s: i for i, s in enumerate(priority)}
        combined["_rank"] = combined["label_source"].map(
            lambda s: source_rank.get(s, len(priority))
        )
        combined = combined.sort_values("_rank")
        combined = combined[~combined.index.duplicated(keep="first")]
        combined = combined.drop(columns=["_rank"])
        logger.info(
            "Merged training set: %d samples (%s)",
            len(combined),
            combined["label_source"].value_counts().to_dict(),
        )
        return combined
